# Generated by Django 4.2.26 on 2025-11-24 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionresult',
            name='corrected_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correctionresult',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='grammar_checker.correctionrequest'),
        ),
    ]
